### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#298]
- [x] Get rid of non-release-version dependencies
    - [x] celery
    - [x] django-formset-js
- [x] Packaging
- [x] Plugin install docs with docker
- [x] Plugin install docs without docker

Before 1.0:
- [x] Check translations
- [x] Test install docs
- [x] Squash migrations
- [x] Write blogpost
- [ ] Notify people
- [x] Adjust Readme

**Comment by raphaelm** [comment]
Notes for people upgrading from pre-1.0.0 (in progress)

* You can keep your source tree and continue updating by git pull, or you switch to pip installation, see docs. Switching should be seamless.
* ``celery -A pretix.celery worker -l info`` is now ``celery -A pretix.celery_app worker -l info``
