### ISSUE TITLE
Release checklist for 1.1.0

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#422]
- [x] Check translations
- [x] Squash migrations and test them
- [x] Prepare blogpost
- [x] Bump version in ``src/pretix/__init__.py``
- [x] Create git branch
- [x] Create git tag
- [x] Upload PyPI package (sdist and wheel)
- [x] Create tag on docker hub
- [x] Check if any official plugins need a release
- [x] Check if pretixdroid needs a release
- [ ] Publish blogpost
