### ISSUE TITLE
Release checklist 1.7.0

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#618]
- [x] Make pretixdroid configuration prettier
- [x] Merge fees branch
- [x] Check translations
- [x] Squash migrations and test them
- [x] Prepare blogpost
- [x] Bump version in ``src/pretix/__init__.py``
- [x] Check that dependencies in setup.py match requirements.txt
- [x] Create git branch
- [x] Create git tag
- [x] Upload PyPI package (sdist and wheel, make sure they are cleanly built)
- [x] Create tag on docker hub
- [x] Check if any official plugins need a release
  - [x] Update sepadebit
- [x] Check if pretixdroid needs a release
- [x] Publish blogpost
- [x] Update data.json
