### ISSUE TITLE
Writable API

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#654]
This is to track the whole progress on adding write operations to our REST API.

- [ ] Orders
  - [x] create (#599, #911)
  - [x] mark paid
  - [x] mark pending
  - [x] mark expired
  - [x] mark canceled
  - [x] mark refunded?
  - [x] extend order
  - [x] change comment
  - [x] create invoice
  - [x] resend link
  - [x] change email address
  - [x] regenerate secrets
  - [x] change locale
  - [x] change invoice address
  - [x] change names, question answers, … (#1904)
  - [x] change positions (ie all orderchangemanager operations)
    - [x] changing the product or variation of a position (#2552)
    - [x] changing the subevent of a position (#2552)
    - [x] changing the seat of a position (#2552)
    - [x] changing the price of a position (#2552)
    - [x] changing the tax rule of a position (#2552)
    - [ ] changing the membership used for a position
    - [x] cancelling a position (already implemented)
    - [x] adding a position (top-level or add-on) (#2552)
    - [x] splitting the order (#2552)
    - [x] changing the value of a fee (#2552)
    - [x] cancelling a fee (#2552)
    - [x] regenerating the secret of a position (#2552)
    - [x] re-calculating all taxes from product and tax rule data (#2552)

- [x] events (#756)
  - [x] create (#756)
  - [x] update (#756)
  - [x] delete
  - [x] settings (#1378)
  - [x] blocked seats
- [x] subevents
  - [x] create (#1217)
  - [x] update (#1217)
  - [x] delete (#1217)
- [x] invoices
  - [x] regenerate
  - [x] reissue
- [x] tax rules
  - [x] create
  - [x] update
  - [x] delete
- [x] categories (#818)
  - [x] create (#818)
  - [x] update (#818)
  - [x] delete (#818)
- [x] items (#676)
  - [x] create (#676)
  - [x] update (#676)
  - [x] delete (#676)
- [x] questions (#813)
  - [x] create (#813)
  - [x] update (#813)
  - [x] delete (#813)
- [x] vouchers
  - [x] create
  - [x] update
  - [x] delete
- [x] waiting list entries (#885)
  - [x] create (#885)
  - [x] update (#885)
  - [x] delete (#885)
  - [x] assign voucher (#885)
- [x] quotas
  - [x] create
  - [x] update
  - [x] delete
- [x] teams
- [x] devices

**Comment by turegjorup** [comment]
Thank you for the overview. We're currently evaluating Pretix, but need create/update on at least events, items and quotas for it to be a viable solution. 

I've been looking into trying to add this, but I have no previous Django experience. I have have basic create/update working by just changing to `class EventViewSet(viewsets.ModelViewSet):`, this however bypasses the validation in `EventWizardBasicsForm`. I have also read your reply to #599 and can see implementing the full API will require some effort.

Have been experimenting with adding slug validation to the `EventSerializer` but this will duplicate code so it's not the best solution it seems. (And so far, I haven't got it working either).

Do you have a plan for how to do validation for both the API and the form views?

**Comment by raphaelm** [comment]
Hi @turegjorup! For not having any Django experience you did an excellent job on correctly identifying what the problems are here :laughing: 

> Thank you for the overview. We're currently evaluating Pretix, but need create/update on at least events, items and quotas for it to be a viable solution.

Your chances are good, I believe items and quotas are comparatively easy to implement and events still doable. The only really near-impossible model to implement the API for well is the order model.

> I've been looking into trying to add this, but I have no previous Django experience. I have have basic create/update working by just changing to class EventViewSet(viewsets.ModelViewSet):, this however bypasses the validation in EventWizardBasicsForm.

Correct. In principle, we only need to drop the ``ReadOnly`` part of the base class, but for every write operation we need to think about

1. validation – this can be something like EventWizardBasics form or even less obvious things like not allowing to delete a product that has already been bought.
2. logging – just as with the form views, we need to write the actions to the event's logs

> Have been experimenting with adding slug validation to the EventSerializer but this will duplicate code so it's not the best solution it seems. (And so far, I haven't got it working either).
> Do you have a plan for how to do validation for both the API and the form views?

Correct, that's what I'm struggling with as well. However, I think it's mostly solved now with the voucher API being implemented as a proof-of-concept:

The shared logic layer below both serializers and views is the model. All validation logic required by both serializer and view should – in my eyes – therefore be in the model. You can see with the voucher model how I created a number of [static validation methods](https://github.com/pretix/pretix/blob/master/src/pretix/base/models/vouchers.py#L198) that I use both [in the form](https://github.com/pretix/pretix/blob/master/src/pretix/control/forms/vouchers.py#L104) and [in the API](https://github.com/pretix/pretix/blob/master/src/pretix/api/serializers/voucher.py#L19). The only duplicate code required this way is some glue code calling those methods with the correct parameters (which is unavoidable in most cases since forms and APIs have different input formats). I think this is clean enough.

If you want to implement this yourself and create a pull request for it, I'd very much support that and am glad to offer any help. If I were you, I'd split the work into three separate PRs and start with the quotas endpoint (it is the simplest because of a relatively flat structure), then go over to items and then do events as the last step. If you don't want to do that but want to use pretix for a commercial event, there is also the possibility to sponsor the work on this feature to move it up on our roadmap (contact sales@pretix.eu in that case) – or wait until we do it anyway ;)
