### ISSUE TITLE
Release checklist 1.9.0

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#667]
- [ ] Deploy to pretix.eu
- [x] Check translations
- [x] Squash migrations and test them
- [x] Prepare blogpost
- [x] Bump version in ``src/pretix/__init__.py``
- [x] Check that dependencies in setup.py match requirements.txt
- [x] Create git branch
- [x] Create git tag
- [x] Upload PyPI package (sdist and wheel, make sure they are cleanly built)
- [x] Create tag on docker hub
- [x] Check if any official plugins need a release
  - [x] Update wirecard
  - [x] Update pages
  - [x] update sepadebit
- [x] Check if pretixdroid needs a release
- [x] Publish blogpost
- [x] Update data.json

**Comment by koebi** [comment]
Actually, translations should be revisited, I created two new pull-requests. The current version is rather probable to break informal german…

**Comment by raphaelm** [comment]
Hmm, I didn't see any mess when making the release (and it's too late now), but I'll have a look at your PRs! :)
