### ISSUE TITLE
Release checklist 1.10.0

### ISSUE THREAD

**Issue by raphaelm** [pretix/pretix#697]
- [x] Merge #693
- [x] Deploy to pretix.eu
- [x] Check translations
- [x] Squash migrations and test them
- [x] Prepare blogpost
- [x] Bump version in ``src/pretix/__init__.py``
- [x] Check that dependencies in setup.py match requirements.txt
- [x] Create git branch
- [x] Create git tag
- [x] Upload PyPI package (sdist and wheel, make sure they are cleanly built)
- [x] Create tag on docker hub
- [x] Check if any official plugins need a release
  - [x] Update newsletter-ml
  - [x] Update printtool
  - [x] Update bounces
- [x] Check if pretixdroid needs a release
- [x] Update data.json
- [x] Publish blogpost
- [x] Social media
